# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

.shared_windows_runners:
  tags:
    - shared-windows
    - windows-1809
  variables:
    VCPKG_ROOT: C:\vcpkg

.shared_linux_runners:
  tags:
    - saas-linux-small-amd64

stages:
  - build
  - prepare
  - release


## ~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
## The Windows build
## ~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=

cmake-windows-native-build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
    - |
      if (!(Test-Path Env:\VCPKG_ROOT)) {
        New-Item -Force -Path Env:\VCPKG_ROOT -Value ${VCPKG_ROOT}
      }
      pushd ${VCPKG_ROOT}
      git checkout master
      git pull --rebase
      popd
    - choco feature enable -n allowGlobalConfirmation
    - choco install -y nsis
    - .\cmake\cmake-builder.ps1 -flavor vs2019 -config Release -clean -parallel -verbose -cpack_suffix win32-native
    - cd cmake\build-vs2019
    - cpack -G "NSIS;ZIP" -C Release
    - cd ..\..
  artifacts:
    when: on_success
    expire_in: 30 days
    name: "simh-4.1.0-win32-vs2019"
    paths:
      - "cmake/build-vs2019/simh-4.1.0-win32-native.zip"
      - "cmake/build-vs2019/simh-4.1.0-win32-native.exe"


## ~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
## Ubuntu 22.04 (jammy)
## ~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=

cmake-ubuntu-jammy-build:
  extends:
    - .shared_linux_runners
  image: ubuntu:jammy
  stage: build
  script:
    - apt update && apt -ym upgrade && apt -y autoremove
    - apt install -ym sudo gcc g++ ninja-build git
    - .travis/deps.sh linux
    - cmake/cmake-builder.sh --config Release --flavor ninja --parallel --verbose --cpack_suffix x86_64-ubuntu22.04
    - cd cmake/build-ninja && cpack -G DEB -C Release
  artifacts:
    when: on_success
    expire_in: 30 days
    name: "simh-4.1.0-x86_64-ubuntu22.04"
    paths:
      - "cmake/build-ninja/simh-4.1.0-x86_64-ubuntu22.04.deb"

prep_release:
  stage: prepare                                              # This stage must run before the release stage
  needs: ["cmake-windows-native-build", "cmake-ubuntu-jammy-build"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH             # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "EXTRA_DESCRIPTION=open-simh-latest release" > variables.env
    - echo "TAG=latest" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env                                   # Use artifacts:reports:dotenv to expose the variables to other jobs

do_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: "cmake-windows-native-build"
      artifacts: true
    - job: "cmake-ubuntu-jammy-build"
      artifacts: true
    - job: "prep_release"
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION and the $TAG
    tag_name: '$TAG'                                                 # variables must be defined elsewhere
    ref: '$CI_COMMIT_SHA'                                            # in the pipeline. For example, in the
    assets:
      links:
        - name: 'simh-4.1.0-x86_64-ubuntu22.04.deb'
          url: "https://gitlab.com/scooter-phd/open-simh/-/jobs/${CI_JOB_ID}/artifacts/file/cmake/build-ninja/simh-4.1.0-x86_64-ubuntu22.04.deb"
        - name: 'simh-4.1.0-win32-native.zip'
          url: 'https://gitlab.com/scooter-phd/open-simh/-/jobs/${CI_JOB_ID}/artifacts/file/cmake/build-vs2019/simh-4.1.0-win32-native.zip'
        - name: 'simh-4.1.0-win32-native.exe'
          url: 'https://gitlab.com/scooter-phd/open-simh/-/jobs/${CI_JOB_ID}/artifacts/file/cmake/build-vs2019/simh-4.1.0-win32-native.exe'
